Repository HACC2020/ByteCryb, pull requests merged in 2020-11, with the labels that each got.

#19 Issue 13
  clio-api/pom.xml
  clio-api/src/main/java/bytecryb/clio/controller/RoleController.java
  clio-api/src/main/java/bytecryb/clio/model/Role.java
  clio-api/src/main/java/bytecryb/clio/repository/RoleRepository.java
Labels: enhancement

#41 Pull Request for Issue 35: Create Jobs Table
  clio-api/src/main/java/bytecryb/clio/controller/JobController.java
  clio-api/src/main/java/bytecryb/clio/controller/placeholder.txt
  clio-api/src/main/java/bytecryb/clio/model/Job.java
  clio-api/src/main/java/bytecryb/clio/model/placeholder.txt
  clio-api/src/main/java/bytecryb/clio/repository/JobRepository.java
  clio-api/src/main/java/bytecryb/clio/repository/placeholder.txt
Labels: enhancement

#52 Pull Request for Issue 51: "Create PDF Table"
  clio-api/pom.xml
  clio-api/src/main/java/bytecryb/clio/config/SecurityConfiguration.java
  clio-api/src/main/java/bytecryb/clio/controller/PDFController.java
  clio-api/src/main/java/bytecryb/clio/controller/placeholder.txt
  clio-api/src/main/java/bytecryb/clio/exception/FileException.java
  clio-api/src/main/java/bytecryb/clio/exception/ResourceNotFoundException.java
  clio-api/src/main/java/bytecryb/clio/exception/UnsupportedFileException.java
  clio-api/src/main/java/bytecryb/clio/exception/placeholder.txt
  clio-api/src/main/java/bytecryb/clio/handler/GlobalExceptionHandler.java
  clio-api/src/main/java/bytecryb/clio/model/HttpError.java
  clio-api/src/main/java/bytecryb/clio/model/PDF.java
  clio-api/src/main/java/bytecryb/clio/model/Record.java
  clio-api/src/main/java/bytecryb/clio/model/placeholder.txt
  clio-api/src/main/java/bytecryb/clio/repository/PDFRepository.java
  clio-api/src/main/java/bytecryb/clio/service/PDFService.java
  clio-api/src/main/resources/application.properties
Labels: enhancement

#55 Pull Request for basic user authentication with no roles
  clio-api/src/main/java/bytecryb/clio/config/CustomJwtAuthenticationFilter.java
  clio-api/src/main/java/bytecryb/clio/config/SecurityConfiguration.java
Labels: enhancement

#68 Pull Request Issue 50:
  clio-api/pom.xml
  clio-api/src/main/java/bytecryb/clio/controller/JobController.java
  clio-api/src/main/java/bytecryb/clio/controller/PDFController.java
  clio-api/src/main/java/bytecryb/clio/controller/RecordController.java
  clio-api/src/main/java/bytecryb/clio/controller/RoleController.java
  clio-api/src/main/java/bytecryb/clio/handler/GlobalExceptionHandler.java
  clio-api/src/main/java/bytecryb/clio/model/Job.java
  clio-api/src/main/java/bytecryb/clio/model/Record.java
  clio-api/src/main/java/bytecryb/clio/repository/placeholder.txt
  clio-api/src/main/java/bytecryb/clio/service/PDFService.java
  clio-api/src/main/resources/application.properties
Labels: enhancement

#67 Pull Request for securing paths based on role
  clio-api/pom.xml
  clio-api/src/main/java/bytecryb/clio/config/CustomJwtAuthenticationFilter.java
  clio-api/src/main/java/bytecryb/clio/config/SecurityConfiguration.java
  clio-api/src/main/java/bytecryb/clio/controller/AwardController.java
  clio-api/src/main/java/bytecryb/clio/controller/BadgeController.java
  clio-api/src/main/java/bytecryb/clio/controller/UserAuthentication.java
  clio-api/src/main/java/bytecryb/clio/controller/UserController.java
  clio-api/src/main/java/bytecryb/clio/model/Award.java
  clio-api/src/main/java/bytecryb/clio/model/Badge.java
  clio-api/src/main/java/bytecryb/clio/model/CustomUser.java
  clio-api/src/main/java/bytecryb/clio/model/Role.java
  clio-api/src/main/java/bytecryb/clio/repository/RoleRepository.java
  clio-api/src/main/java/bytecryb/clio/service/CustomUserDetailsService.java
  clio-api/src/main/java/bytecryb/clio/util/JwtUtil.java
  clio-api/src/main/resources/application-dev.properties
  clio-api/src/main/resources/application-prod.properties
  clio-api/src/main/resources/import.sql
Labels: enhancement

#69 Pull Request on signup, user is given authToken and password is not shown
  clio-api/src/main/java/bytecryb/clio/controller/UserAuthentication.java
  clio-api/src/main/java/bytecryb/clio/model/ResultUser.java
Labels: bug

#71 One to many and many to one relationship for records and jobs
  clio-api/src/main/java/bytecryb/clio/model/Job.java
  clio-api/src/main/java/bytecryb/clio/model/Record.java
Labels: enhancement

#82 Pull Request for Issue 77: User endpoint for general user info (username, role name, score, badges)
  clio-api/pom.xml
  clio-api/src/main/java/bytecryb/clio/config/SecurityConfiguration.java
  clio-api/src/main/java/bytecryb/clio/controller/ScoreController.java
  clio-api/src/main/java/bytecryb/clio/controller/UserController.java
  clio-api/src/main/java/bytecryb/clio/model/Award.java
  clio-api/src/main/java/bytecryb/clio/model/Badge.java
  clio-api/src/main/java/bytecryb/clio/model/CustomUser.java
  clio-api/src/main/java/bytecryb/clio/repository/AwardRepository.java
  clio-api/src/main/java/bytecryb/clio/repository/BadgeRepository.java
  clio-api/src/main/java/bytecryb/clio/repository/ScoreRepository.java
  clio-api/src/main/java/bytecryb/clio/repository/UserRepository.java
  clio-api/src/main/resources/application-dev.properties
  clio-api/src/main/resources/import.sql
Labels: enhancement

#73 Create unidirectional one to one relation between record and pdf class
  clio-api/src/main/java/bytecryb/clio/model/Award.java
  clio-api/src/main/java/bytecryb/clio/model/Badge.java
  clio-api/src/main/java/bytecryb/clio/model/CustomUser.java
  clio-api/src/main/java/bytecryb/clio/model/PDF.java
  clio-api/src/main/java/bytecryb/clio/model/Record.java
  clio-api/src/main/java/bytecryb/clio/model/Role.java
  clio-api/src/main/java/bytecryb/clio/model/Score.java
Labels: enhancement

#72 One to many & many to one relationship between categories and jobs
  clio-api/src/main/java/bytecryb/clio/model/Job.java
  clio-api/src/main/java/bytecryb/clio/model/Record.java
Labels: enhancement

#83 Pull request for Issue 65, scoreboard api endpoints
  clio-api/src/main/java/bytecryb/clio/controller/ScoreController.java
  clio-api/src/main/java/bytecryb/clio/controller/UserAuthentication.java
  clio-api/src/main/java/bytecryb/clio/model/Score.java
  clio-api/src/main/java/bytecryb/clio/service/ScoreService.java
Labels: enhancement

#95 Pull Request for Issue 87: Fixed api endpoints for scores
  clio-api/src/main/java/bytecryb/clio/controller/ScoreController.java
  clio-api/src/main/java/bytecryb/clio/controller/UserAuthentication.java
  clio-api/src/main/java/bytecryb/clio/controller/UserController.java
  clio-api/src/main/java/bytecryb/clio/model/ResultScore.java
  clio-api/src/main/java/bytecryb/clio/model/Score.java
  clio-api/src/main/java/bytecryb/clio/repository/ScoreRepository.java
  clio-api/src/main/java/bytecryb/clio/service/ScoreService.java
  clio-api/src/main/resources/import.sql
Labels: bug

#102 Pull Request for Issue 101
  clio-api/pom.xml
  clio-api/src/main/java/bytecryb/clio/controller/JobController.java
  clio-api/src/main/java/bytecryb/clio/controller/RecordController.java
  clio-api/src/main/java/bytecryb/clio/repository/RecordRepository.java
Labels: enhancement

#112 Pull Request for Issue 111: All time scores endpoint now work properly
  clio-api/src/main/java/bytecryb/clio/controller/ScoreController.java
  clio-api/src/main/java/bytecryb/clio/repository/ScoreRepository.java
Labels: bug

#119 Pull Request for Issue 114
  clio-api/src/main/java/bytecryb/clio/controller/XMLController.java
  clio-api/src/main/java/bytecryb/clio/model/Badge.java
  clio-api/src/main/java/bytecryb/clio/model/CustomUser.java
  clio-api/src/main/java/bytecryb/clio/model/ResultUser.java
Labels: documentation

#124 Pull Request for Issue-123: Endpoint now changes current user role only
  clio-api/src/main/java/bytecryb/clio/controller/UserController.java
Labels: bug

#132 Pull Request for Issue 122
  clio-api/src/main/java/bytecryb/clio/controller/JobController.java
  clio-api/src/main/java/bytecryb/clio/controller/PDFController.java
  clio-api/src/main/java/bytecryb/clio/controller/RecordController.java
  clio-api/src/main/java/bytecryb/clio/service/PDFService.java
Labels: enhancement

#128 Pull request for Issue 100, google signup/login
  clio-api/pom.xml
  clio-api/src/main/java/bytecryb/clio/config/CustomJwtAuthenticationFilter.java
  clio-api/src/main/java/bytecryb/clio/config/SecurityConfiguration.java
  clio-api/src/main/java/bytecryb/clio/controller/ScoreController.java
  clio-api/src/main/java/bytecryb/clio/controller/UserAuthentication.java
  clio-api/src/main/java/bytecryb/clio/exception/SignupTakenException.java
  clio-api/src/main/java/bytecryb/clio/repository/UserRepository.java
  clio-api/src/main/java/bytecryb/clio/service/CustomUserDetailsService.java
  clio-api/src/main/java/bytecryb/clio/util/JwtUtil.java
  clio-api/src/main/resources/application-dev.properties
Labels: enhancement

#99 Pull Request for Issue 96, try/catch for user signup/login
  clio-api/src/main/java/bytecryb/clio/config/SecurityConfiguration.java
  clio-api/src/main/java/bytecryb/clio/controller/UserAuthentication.java
Labels: bug

#146 Pull request for Issue 141, added points column to jobs and made default points set to 5
  clio-api/src/main/java/bytecryb/clio/controller/JobController.java
  clio-api/src/main/java/bytecryb/clio/model/Job.java
  clio-api/src/main/resources/import.sql
Labels: enhancement

#86 Pull request for Issue 81, auth token gets sent in header now
  clio-api/src/main/java/bytecryb/clio/controller/UserAuthentication.java
Labels: enhancement

#167 profile pic support added
  clio-api/src/main/java/bytecryb/clio/controller/UserController.java
  clio-api/src/main/java/bytecryb/clio/model/CustomUser.java
  clio-api/src/main/java/bytecryb/clio/model/ProfilePic.java
  clio-api/src/main/java/bytecryb/clio/repository/ProfilePicRepository.java
  clio-api/src/main/java/bytecryb/clio/service/ProfilePicService.java
Labels: back-end, enhancement

#169 Pull Request for Issue 166
  clio-api/src/main/java/bytecryb/clio/controller/AwardController.java
  clio-api/src/main/java/bytecryb/clio/model/Award.java
  clio-api/src/main/java/bytecryb/clio/repository/BadgeRepository.java
  clio-api/src/main/resources/import.sql
Labels: back-end, enhancement
